my:
  uuid: ${random.uuid}
  name: jiangxia
  age: 29
  email: ${random.email}
  greeting: hi,i'm  ${my.name}

person:
  #  单引号会将\n作为字符串输出，双引号会将\n换行输出：所以双引号不会进行转义，而单引号会转义，因为\n本来就是转义换行的意思
  #  -n表示N大写，等同于userName
  user-name: 张三
  boss: true
  #  默认时间格式是/
  birth: 2020/12/29
  age: 18
  phone:
    band: 华为
    price: 6000.00
  #  interests: [篮球,足球]等同于下面格式
  #    -代表一个元素
  interests:
    - 篮球
    - 足球
    - 18
    - 175158455
  animal: [猫,狗]
  #  score: {english:80,math:90}
  score:
    english: 80
    math: 90
  salarys:
    - 9999.98
    - 9999.99
  allPhones:
    china:
      - {band: 华为,price: 6000.00}
      - band: 小米
        price: 5000.98
      - band: oppo
        price: 4000.36
    America: [{band: Iphone,price: 7000.23},{band: nokia,price: 4002.36}]


server:
  port: 8081
  servlet:
    context-path: /share
spring:
  application:
    name: share
  servlet:
    multipart:
#      单个文件最大限制 类型是datasize，单位kb
      max-file-size: 1024
#      单次请求最大限制
      max-request-size: 2048
  datasource:
    dynamic:
      primary: db1 # 配置默认数据库
    db1:
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Chongqing&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
      username: root
      password: jiang
      driver-class-name: com.mysql.cj.jdbc.Driver
    db2:
      jdbc-url: jdbc:mysql://localhost:3306/spring_cache?serverTimezone=Asia/Chongqing&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&verifyServerCertificate=false&autoReconnct=true&autoReconnectForPools=true&allowMultiQueries=true
      username: root
      password: jiang
      driver-class-name: com.mysql.cj.jdbc.Driver
    ## sql server
    #url: jdbc:sqlserver://10.100.2.60:1420;DatabaseName=ResumeCenter
    #driver-class:  com.microsoft.sqlserver.jdbc.SQLServerDriver
  #redis配置
  redis:
    #redis数据库索引（默认为0）
    database: 0
    #redis服务器地址
    #docker redis服务器地址
    host: 192.168.42.100
    # 本地redishost地址
    #host: 127.0.0.1
    #redis链接端口
    post: 6379
    #Redis服务器连接密码（默认为空）
    password:
    pool:
    # 连接池最大连接数（使用负值表示没有限制）
      max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
    # 连接池中的最大空闲连接
      max-idle: 10
    # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间毫秒
    timeout: 1000
#  rabbitmq配置
  rabbitmq:
#    host: 192.168.42.100  docker
    host: localhost  # 本地
    username: guest
    password: guest
#    端口不写默认就是5672
#    port: 5672

mybatis:
  configuration:
    #开启驼峰命名匹配规则
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring.springbootdemo.bean
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
### Mybatis 配置
## 配置为 com.pancm.bean 指向实体类包路径。
#mybatis:
#  typeAliasesPackage:com.jiang.springbootdemo02.bean
#  # 配置为 classpath 路径下 mapper 包下，* 代表会扫描所有 xml 文件。
##  mapperLocations:classpath\:mapper/*.xml
##log
logging:
  config: /workspace/java/SpringBootWorkSpace/src/main/resources/locbak.xml
  level:
    root: info
    com.springboot.springbootdemo.controller: trace
    com.springboot.springbootdemo.service: debug
    com.springboot.springbootdemo.dao: debug